name: WordPress Deploy 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: wordpress

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to the server.
        run: |
          pwd
          ls -al
          cp -r ./* /var/www/html/wordpress/
          
